name: Develop branch workflow
on:
  pull_request:
    types:
      - opened
    branches:
      - develop

jobs:
  sample:
    name: Test job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Output test message
        run: echo -e "Push develop branch."
