name: Feature branch workflow
on:
  push:
    branches:
      - feature/*

jobs:
  sample:
    name: Test job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Output test message
        run: echo -e "Push feature branch."
